In [1]:
import numpy as np

In [3]:
array = np.array([0,1,2,3,4])
print(array)

[0 1 2 3 4]


In [5]:
array2 = np.array([[0,1,2],[3,4,5]])
print(array2)

[[0 1 2]
 [3 4 5]]


In [6]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
print(arr3.shape)  
print(arr3.size) 
print(arr3.dtype) 


(2, 2, 2)
8
int64


In [8]:
arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
arr = np.random.rand(3, 3) 
print(arr)

[[0.18931854 0.96591089 0.43859317]
 [0.33627262 0.88986587 0.17182809]
 [0.54294315 0.97958465 0.55005969]]


In [11]:
arr = np.random.randint(1, 10, (2, 3))
print(arr)

[[8 7 7]
 [8 8 3]]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # Converts into 2x3 matrix
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(matrix, axis=0))  # Sum of each column
print(np.sum(matrix, axis=1))  # Sum of each row

[5 7 9]
[ 6 15]


In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


In [16]:
data = np.random.randint(50, 100, size=(5, 3))  # Random 5x3 dataset
print("Dataset:\n", data)

# Column-wise analysis
print("Mean of each column:", np.mean(data, axis=0))
print("Max of each column:", np.max(data, axis=0))
print("Min of each column:", np.min(data, axis=0))
print("Median:"), np.median(data,axis=0)


Dataset:
 [[69 83 62]
 [71 63 94]
 [56 81 61]
 [62 87 60]
 [87 97 93]]
Mean of each column: [69.  82.2 74. ]
Max of each column: [87 97 94]
Min of each column: [56 63 60]
Median:


(None, array([69., 83., 62.]))

In [19]:
data = np.random.randint(50, 100, size=(5, 3))  # Random 5x3 dataset
print("Dataset:\n", data)
np.save("data.npy", data)# Save array to a file
loaded_arr = np.load("data.npy")  # Load it back
print(data)

Dataset:
 [[67 99 97]
 [88 66 77]
 [87 66 86]
 [92 76 72]
 [84 95 75]]
[[67 99 97]
 [88 66 77]
 [87 66 86]
 [92 76 72]
 [84 95 75]]


In [25]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
arr2 = np.random.randint(11,20,(2,5))
print(arr2)

[[19 12 18 15 17]
 [18 11 12 17 15]]


In [29]:
print(arr1.shape)
print(arr2.shape)

(10,)
(2, 5)


In [30]:
print(arr1.size)
print(arr2.size)

10
10


In [31]:
print(arr1.dtype)
print(arr2.dtype)

int64
int32


In [32]:
arr = np.array([5, 10, 15, 20, 25])
print(arr)
print(arr*2)

[ 5 10 15 20 25]
[10 20 30 40 50]


In [35]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)
print(arr1)
print("\n")
print(arr2)
print("\n")
print(arr1+arr2)

[[0.27374392 0.58402173 0.09822594]
 [0.84040167 0.05799189 0.95804082]
 [0.55165548 0.33295221 0.01250597]]


[[0.75873795 0.67229992 0.95848081]
 [0.65635782 0.72301858 0.34553416]
 [0.25904425 0.33061271 0.04948859]]




TypeError: only integer scalar arrays can be converted to a scalar index

In [36]:
print(arr1.dot(arr2))

[[0.616472   0.63877132 0.46903882]
 [0.92388304 0.92367166 0.87295914]
 [0.64033733 0.6157432  0.64441645]]


In [37]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [41]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat[0])

[1 2 3]


In [43]:
print(mat[:,1])

[2 5 8]


In [44]:
print(mat[-1,-1])

9
